AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM 스터디 목적

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldFunction: # deploy invoke,deploy 할 function 변수
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      #CodeUri: hello_world/ # 경로
      Handler: lambda_function.lambda_handler # 함수 이름
      Runtime: python3.8
      Environment:
        Variables:
          ACCESS_KEY: your_access_key
          SECRET_KEY: your_secret_key
          HOST: db_host
          DATABASE: db_name
          PASSWORD: user_password
          USER: user_name
